name: Optimize map and deploy

on:
  push:
    paths:
      - 'map/**'
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: ↩️ Checkout
        uses: actions/checkout@v2

      - name: 🏗️ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 🏗️ Install packages
        run: cd map && npm ci

      - name: ⚙️ Pack Scripts
        run: cd map && npm run build

      - name: ⚙️ Optimize map
        uses: thecodingmachine/map-optimizer-action@master
        with:
          map-file: map/quest-for-coffee.json

      - name: 📦 Package deployment
        run: |
          mkdir deploy
          cp map/quest-for-coffee.json deploy/
          cp map/dist/* deploy/
          cp -R map/assets deploy/
          ls -al deploy

      - name: 🚐 Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: deploy
          target-folder: map
          clean: "false"